### PR TITLE
Find only the malicious workflow on repositories with lot of actions

### PR DESCRIPTION
**Pull request by rtrompier**
Find only the malicious workflow, in case or there is lot of actions running on the tested repository

### CODE REVIEW

**Comment by AdnaneKhan** [comment]
Thank you for the PR and for catching a bug!

To clarify here - the issue you are having is that if the repository has existing workflows that run on `pull_request` gato might get the other one first and then will fail to process the results (because they are not the workflow that Gato added)?

**Comment by rtrompier** [comment]
Yes exactly :) 
Thank you for fixing tests.

**Comment by AdnaneKhan** [comment]
Thank you for your contribution! I've merged it into dev for now. #45 fixes a bug with secret decryption, and we'll add some new integration test cases to cover edge cases and get the updated secrets exfil into main soon.

**Comment by rtrompier** [comment]
Nice ! #45 is very use full because I have the same problem on my side.
Let me know when it will be released ;) 
Thank you.

**Pull request merged**
